### ISSUE TITLE
iOS 8 设备能收的 payload 长度是 2KB 而不是 256B

### ISSUE THREAD

**Issue by lexrus** [huangnaiang/xinge-node-sdk#1]
https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html#//apple_ref/doc/uid/TP40008194-CH100-SW1

> Each remote notification includes a payload. The payload contains information about how the system should alert the user as well as any custom data you provide. In iOS 8 and later, the maximum size allowed for a notification payload is 2 kilobytes; Apple Push Notification service refuses any notification that exceeds this limit. (Prior to iOS 8 and in OS X, the maximum payload size is 256 bytes.)

貌似 Apple 已经在去年 9 月左右部署了这一改动，信鸽这边能不能去掉 256 字节的限制？

**Comment by huangnaiang** [comment]
我反馈给项目组
