### ISSUE TITLE
推送的api里面没有批量设备推送的接口

### ISSUE THREAD

**Issue by xueling795** [huangnaiang/xinge-node-sdk#2]
Xinge.js里面没有定义http://openapi.xg.qq.com/v2/push/create_multipush 这个接口没有实现，难道群发设备需要循环调用 single 的api?

**Comment by huangnaiang** [comment]
Xinge Node SDK 已经不更新了

**Comment by xueling795** [comment]
把我加到 repository 里，我来更新：)

**Comment by huangnaiang** [comment]
已添加 :-)
